language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
    # maintainers to fix their pypy-dev package.
    - "pypy"

before_install:
    - sudo apt-get update
    - sudo apt-get install --assume-yes fonts-liberation libappindicator1
    - wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i /tmp/chrome.deb
    - sudo apt-get install xvfb
    - export CHROME_BIN=google-chrome-stable
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &


# command to install dependencies
install:
    # - pip install .
    - pip install -r requirements.txt

# command to run tests
script:
    - nosetests -v --with-xunit --with-coverage --cover-erase --cover-package=atve

after_success:
    - coveralls
