sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
    # maintainers to fix their pypy-dev package.
    - "pypy"

# command to install dependencies
install:
    # - pip install .
    - pip install -r requirements-travis.txt

# command to run tests
script:
    - nosetests -v test/test_* --with-xunit --with-coverage --cover-erase --cover-package=atve

after_success:
    - coveralls
