language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
    # maintainers to fix their pypy-dev package.
    - "pypy"

before_install:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update
    - sudo apt-get install google-chrome-stable xvfb
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &


# command to install dependencies
install:
    # - pip install .
    - pip install -r requirements.txt

# command to run tests
script:
    - nosetests -v --with-xunit --with-coverage --cover-erase --cover-package=atve

after_success:
    - coveralls
